// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cijnmyiffzwwujkpjqiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpam5teWlmZnp3d3Vqa3BqcWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0NDkxMjksImV4cCI6MjA5OTAyNTEyOX0.yon_Dka2yDkH6991B0MYH05kDRrt948qOYpYVySWWwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});